Himenon/openapi-typescript-code-generator

.dependency-cruiser.js
README.md
example/codegen.ts
package.json
scripts/testCodeGen.ts
src/index.ts

* fix document lang
* remote version argument
* typescript: dependencies -> peerDependencies

fix: after release some bugs

---

README.md
docs/ja/README-ja.md
example/sample-axios.ts
example/sample-debug.ts
example/sample-fetch.ts
example/sample-superagent.ts
example/utils.ts
src/Converter/v3/components/Schema.ts
src/Converter/v3/components/Schemas.ts
src/Converter/v3/toTypeNode.ts
test/__tests__/__snapshots__/snapshot-test.ts.snap
test/api.test.domain/index.yml

```yml
DeepObjectParameter:
description: deepObject
required: true
in: query
name: filter
schema:
type: object
additionalProperties:
type: object
properties:
gt:
type: string
gte:
type: string
lt:
type: string
lte:
type: string
any:
oneOf:
- type: string
- type: number
- type: boolean
```

chore: fix bugs and update docs

---

src/Converter/v3/Context.ts
src/Converter/v3/components/Header.ts
src/Converter/v3/components/Operation.ts
src/Converter/v3/components/Parameter.ts
src/Converter/v3/components/Parameters.ts
src/Converter/v3/components/Response.ts
src/Converter/v3/components/Responses.ts
src/Converter/v3/components/Schemas.ts
src/Converter/v3/store/Store.ts
src/Converter/v3/toTypeNode.ts
test/__tests__/__snapshots__/snapshot-test.ts.snap
test/api.test.domain/index.yml

fix: https://github.com/Himenon/openapi-typescript-code-generator/issues/7

fix: unresolved reference

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
scripts/testCodeGen.ts
src/Validator/v3/openapi.json
test/api.test.domain/index.yml

fix(vadliation): example property

---

src/Converter/v3/components/Header.ts
src/Converter/v3/components/Headers.ts
src/Converter/v3/components/MediaType.ts
src/Converter/v3/components/Parameter.ts
src/Converter/v3/components/Parameters.ts
src/Converter/v3/components/PathItems.ts
src/Converter/v3/components/RequestBodies.ts
src/Converter/v3/components/RequestBody.ts
src/Converter/v3/components/Responses.ts
src/Converter/v3/components/Schema.ts
src/Converter/v3/components/Schemas.ts
src/Converter/v3/components/SecuritySchemas.ts
test/__tests__/__snapshots__/snapshot-test.ts.snap
test/api.test.domain/components/parameters/ForPathItems/FullRemoteReference.yml
test/api.test.domain/components/responses/ForPathItems/FullRemoteReference.yml
test/api.test.domain/components/responses/ResponseA.yml

* [this](https://github.com/Himenon/openapi-typescript-code-generator/pull/19/files#diff-39f69e8343b49877f95cf8059733286481a9a0b64781e71fe1de4681b1b5e82a)

feat(comment): Use the defined comment

---

.github/workflows/build.yml
package.json
scripts/tools/copyPackageSet.ts
src/CodeGenerator/factory/utils.ts
src/Converter/v3/TypeNodeContext.ts
src/Converter/v3/components/Reference.ts
src/Converter/v3/components/Response.ts
src/Converter/v3/components/Responses.ts
src/Converter/v3/store/Store.ts
src/DefaultCodeTemplate/ApiClientClass/MethodBody/__tests__/PathParameter-test.ts
yarn.lock

feat: support for windows

---

scripts/tools/copyPackageSet.ts
src/Converter/v3/TypeNodeContext.ts
src/Converter/v3/components/Reference.ts
src/Converter/v3/components/Response.ts
src/Converter/v3/components/Responses.ts
src/Converter/v3/store/Store.ts

This PR solves the problem that it doesn't work in Windows environment. Fixes the problem caused by using the `path` module to resolve the path of OpenAPI.
To solve this problem, the related library needs to be fix.
depended PR: https://github.com/Himenon/path-oriented-data-structure/pull/3
Works fine on my windows machine. Correctly process the Component described in the file and described in the external file.

fix: support for windows

---

package.json
scripts/build.ts
scripts/tools/copyPackageSet.ts
scripts/tools/dualPackageSupport.ts
src/Validator/v3/index.ts
src/api.ts
yarn.lock

feat: support dual package

---

README.md
docs/ja/README-ja.md

docs(readme): update

---

src/internal/OpenApiTools/Walker/Operation.ts
src/internal/OpenApiTools/Walker/Store.ts
src/internal/OpenApiTools/components/Operation.ts
src/internal/OpenApiTools/components/Parameter.ts
src/internal/OpenApiTools/components/PathItem.ts
src/typedef/OpenApi.ts
test/__tests__/__snapshots__/parameter-test.ts.snap
test/__tests__/__snapshots__/spit-code-test.ts.snap
test/__tests__/__snapshots__/template-only-test.ts.snap
test/__tests__/__snapshots__/typedef-with-template-test.ts.snap
test/api.test.domain/index.yml

fix: https://github.com/Himenon/openapi-typescript-code-generator/issues/47

fix: pathItem's parameters field support

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
README.md
docs/ja/README-ja.md

Because GitHub Pages has exceeded its hosting capacity.

docs: update playground url

---

src/internal/OpenApiTools/components/Parameter.ts

This PR solves the problem that required field for Parameter(LocalReference) is not enabled(always `optional: false`).
The following yaml is processed correctly.
```yaml
openapi: 3.0.0
info:
version: 0.0.1
paths:
/test:
get:
operationId: Test
parameters:
- $ref: '#/components/parameters/Requied'
- $ref: '#/components/parameters/Optional'
components:
parameters:
Requied:
in: query
name: requied
description: required parameter
required: true
schema:
type: integer
format: int32
example: 1
Optional:
in: query
name: optional
description: optional parameter
required: false
schema:
type: integer
format: int32
example: 2
```

Local reference parameter required

---

src/code-templates/api-client/ApiClientClass/MethodBody/PathParameter.ts
src/internal/TsGenerator/factory/RegularExpressionLiteral.ts
src/internal/TsGenerator/factory/index.ts
test/__tests__/__snapshots__/spit-code-test.ts.snap
test/__tests__/__snapshots__/template-only-test.ts.snap
test/__tests__/__snapshots__/typedef-with-template-test.ts.snap

Invalid code
```js
let baseUrl = "https://api.example.com/"
....
baseUrl + "/a/b/c";
```
Code that works reliably
```js
let baseUrl = "https://api.example.com/"
....
baseUrl.replace(/\/$/, "") + "/a/b/c";
```

fix: Trim the trailing slash of baesUrl

---

src/code-templates/api-client/ApiClientClass/Class.ts
src/code-templates/api-client/ApiClientClass/Constructor.ts
src/code-templates/api-client/ApiClientClass/MethodBody/PathParameter.ts
src/internal/TsGenerator/factory/BinaryExpression.ts
src/internal/TsGenerator/factory/ExpressionStatement.ts
src/internal/TsGenerator/factory/PropertyDeclaration.ts
src/internal/TsGenerator/factory/index.ts
test/__tests__/__snapshots__/spit-code-test.ts.snap
test/__tests__/__snapshots__/template-only-test.ts.snap
test/__tests__/__snapshots__/typedef-with-template-test.ts.snap

chore: Trim the trailing slash of the baseUrl with constructor

---

src/internal/OpenApiTools/components/PathItem.ts
src/internal/ResolveReference/index.ts

* Fixed a bug where properties with '.' as a key were not referenced
```yaml
components:
schemas:
components:
"v1.hoge":
type: string
requestBodies:
sample:
$ref: "#/components/schemas/v1.hoge"
```

fix: Fixed a bug where properties with '.' as a key were not referenced

---

src/code-templates/api-client/ApiClientClass/MethodBody/PathParameter.ts
src/code-templates/api-client/__tests__/utils.test.ts
src/code-templates/api-client/utils.ts
src/utils.ts
test/__tests__/__snapshots__/parameter-test.ts.snap
test/__tests__/__snapshots__/spit-code-test.ts.snap
test/__tests__/__snapshots__/template-only-test.ts.snap
test/__tests__/__snapshots__/typedef-with-template-test.ts.snap
test/api.test.domain/index.yml

Support below schema.
```yml
/get/search/{book.name}: // <--- book.name
get:
operationId: searchBook
parameters:
- in: path
name: book.name
required: true
schema:
type: string
responses:
200:
description: Search Book Result
content:
application/json: 
schema:
type: object
properties:
id:
type: number
bookTitle:
type: string
```
* https://github.com/argoproj/argo-cd/blob/master/assets/swagger.json

fix(path-parameter): Support element access

---

src/code-templates/api-client/ApiClientClass/MethodBody/index.ts
test/__tests__/__snapshots__/parameter-test.ts.snap
test/__tests__/__snapshots__/spit-code-test.ts.snap
test/__tests__/__snapshots__/template-only-test.ts.snap
test/__tests__/__snapshots__/typedef-with-template-test.ts.snap
test/api.test.domain/index.yml

* related: #67 
```yml
/get/search/{book.name}:
get:
operationId: searchBook
parameters:
- in: path
name: book.name
required: true
schema:
type: string
- in: query
name: from.publishedAt // <--- here
schema:
type: integer
format: int32
```

fix(query-parameter): Support element access

---

src/internal/OpenApiTools/toTypeNode.ts
test/__tests__/__snapshots__/typedef-only-test.ts.snap
test/__tests__/__snapshots__/typedef-with-template-test.ts.snap
test/infer.domain/index.yml

GitHub OpenAPI Schemas has below
```yml
schemas:
integration:
type: object
properties:
permissions:
description: The set of permissions for the GitHub app
type: object
properties:
issues:
type: string
checks:
type: string
metadata:
type: string
contents:
type: string
deployments:
type: string
additionalProperties:
type: string
example:
issues: read
deployments: write
```

feat: Updated behaviour of AdditionalProperties when owning OptionalPropery

---

README.md
docs/ja/README-ja.md
scripts/build.ts

fix: test failed

---

src/internal/OpenApiTools/components/Schema.ts
src/internal/OpenApiTools/components/Schemas.ts
test/__tests__/__snapshots__/spit-code-test.ts.snap
test/__tests__/__snapshots__/typedef-only-test.ts.snap
test/__tests__/__snapshots__/typedef-with-template-test.ts.snap
test/api.test.domain/index.yml

fix: make nullable work in components/schema

---

src/code-templates/functional-api-client/FunctionalApiClient/ClientTypeDefinition.ts
src/code-templates/functional-api-client/index.ts
src/meta.ts
test/__tests__/functional/__snapshots__/argo-rollout-test.ts.snap
test/__tests__/functional/__snapshots__/format.domain.ts.snap
test/__tests__/functional/__snapshots__/multi-type.test.domain.ts.snap
test/__tests__/functional/__snapshots__/spit-code-test.ts.snap
test/__tests__/functional/__snapshots__/template-only-test.ts.snap
test/__tests__/functional/__snapshots__/typedef-with-template-test.ts.snap
test/__tests__/functional/__snapshots__/unknown-schema-domain-test.ts.snap

```ts
type ClientFunction<RequestOption> = typeof createClient<RequestOption>;
export type Client<RequestOption> = ReturnType<ClientFunction<RequestOption>>;
```

fix: export type Client for FunctionalApiClient

---

src/code-templates/_shared/ApiClientInterface.ts
src/code-templates/_shared/MethodBody/index.ts
test/__tests__/class/__snapshots__/argo-rollout-test.ts.snap
test/__tests__/class/__snapshots__/format.domain.ts.snap
test/__tests__/class/__snapshots__/multi-type.test.domain.ts.snap
test/__tests__/class/__snapshots__/spit-code-test.ts.snap
test/__tests__/class/__snapshots__/template-only-test.ts.snap
test/__tests__/class/__snapshots__/typedef-with-template-test.ts.snap
test/__tests__/class/__snapshots__/unknown-schema-domain-test.ts.snap
test/__tests__/functional/__snapshots__/argo-rollout-test.ts.snap
test/__tests__/functional/__snapshots__/format.domain.ts.snap
test/__tests__/functional/__snapshots__/multi-type.test.domain.ts.snap
test/__tests__/functional/__snapshots__/spit-code-test.ts.snap
test/__tests__/functional/__snapshots__/template-only-test.ts.snap
test/__tests__/functional/__snapshots__/typedef-with-template-test.ts.snap
test/__tests__/functional/__snapshots__/unknown-schema-domain-test.ts.snap

According to the [OpenAPI 3.0 Specification](https://swagger.io/docs/specification/describing-request-body/#:~:text=The%20payload%20format%20is%20similar%20to%20query%20parameters.), type of `style` property  in requestEncodings can be `"form" | "spaceDelimited" | "pipeDelimited" | "deepObject"` instead of string.
```diff
export interface Encoding {
contentType?: string;
headers?: Record<string, any>;
-  style?: string;
+  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
explode?: boolean;
allowReserved?: boolean;
}
```
```diff
- const requestEncodings = {
+ const requestEncodings: Record<string, Record<string, Encoding>> = {
"application/x-www-form-urlencoded": {
"foo": {
style: "form",
explode: true,
},
},
};
```

fix: type of style property in requestEncodings

---

src/code-templates/_shared/MethodBody/PathParameter.ts
src/code-templates/_shared/MethodBody/__tests__/PathParameter-test.ts
src/code-templates/_shared/__tests__/utils.test.ts
test/__tests__/class/__snapshots__/typedef-with-template-test.ts.snap
test/__tests__/functional/__snapshots__/typedef-with-template-test.ts.snap
test/ref.access/index.yml

fix: separated strings are not restored correctly

---

.dependency-cruiser.cjs
package.json
pnpm-lock.yaml

When using the openapi-typescript-code-generator as CJS, the following error occurs.
```sh
❯ node --input-type=commonjs -e "require('./dist/index.cjs')"
/Users/kei_sakamoto/workspace/openapi-typescript-code-generator/dist/index.cjs:1377
var DotProp2 = __toESM(require("dot-prop"), 1);
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/kei_sakamoto/workspace/openapi-typescript-code-generator/node_modules/.pnpm/dot-prop@8.0.2/node_modules/dot-prop/index.js from /Users/kei_sakamoto/workspace/openapi-typescript-code-generator/dist/index.cjs not supported.
Instead change the require of index.js in /Users/kei_sakamoto/workspace/openapi-typescript-code-generator/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> …
```

fix(build): bundle pure esm package
